cc_library(
  name = "big_number",
  srcs = [
    "integer.cc",
  ],
  hdrs = [
    "integer.h",
    "number.h",
    "real.h",
  ],
  visibility = [ "//visibility:public" ],
  deps = [ "//base" ],
)

cc_library(
  name = "complex_number",
  srcs = [],
  hdrs = [
    "complex.h",
  ],
  visibility = [ "//visibility:public" ],
  deps = [ "//base" ],
)
