language: cpp

compiler:
  - clang

sudo: false

cache: apt

addons:
  apt:
    packages:
    - libgflags-dev
    - libgoogle-glog-dev
    - libstdc++-4.8-dev
    - ninja-build
    - cmake

script:
  - ./build/travis.sh
