version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build and test
          # TODO: Set up a Dockerfile for this.
          # TODO: Check in unit-test specific files in this repository
          command: |
            apt-get update
            apt-get install -y git clang cmake ninja-build libgflags-dev libgoogle-glog-dev
            git submodule init
            git submodule update
            ./build/ci.sh
