cc_library(
  name = "api",
  hdrs = [ "computer.h" ],
  deps = [
    "//base",
  ],
  visibility = [ "//visibility:public" ],
)

cc_library(
  name = "computer",
  srcs = [ "computer.cc" ],
  hdrs = [ "computer.h" ],
  deps = [
    "//base",
    "//drm",
    "//number:big_number",
  ],
  visibility = [ "//visibility:public" ],
)
