cc_library(
  name = "base",
  srcs = [ "base.cc" ],
  hdrs = [ "base.h" ],
  visibility = [ "//visibility:public" ],
  deps = [
    "@com_github_google_glog//:glog",
    "@com_github_gflags_gflags//:gflags",
  ],
)
