cc_library(
  name = "drm",
  srcs = [
    "chudnovsky.cc",
    "drm3.cc",
  ],
  hdrs = [
    "chudnovsky.h",
    "drm3.h",
  ],
  visibility = [ "//visibility:public" ],
  deps = [
    "//base",
    "//computer:api",
    "//number:big_number",
  ],
)
